name: city_stasher_lite
description: Mini app for CityStasher API implementation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.3
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  infinite_scroll_pagination: ^3.2.0
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  logger: ^1.4.0
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  retrofit_generator: ">=5.0.0 <6.0.0"
  freezed: ^2.3.3
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
